identificacao:
  description: >
    1. Identificar qual é a área do problema recebido
    2. Passar para o agente responsável pela área o  seguinte problema: {problema}.
  expected_output: >
    Passar o problema para o agente responsável pela área.
  agent: identificador


solucao_juridica:
  description: >
    1. De acordo com o problema crie um documento com soluções para o problema: {problema}.
    2. As seções/subtítulos devem ser nomeados de maneira envolvente.
    3. Caso o problema não seja de sua área não faça nada
  expected_output: >
    aso o problema seja de sua área, envie esse documento para o Supervisor de artigos
  agent: juridico


solucao_tecnica:
  description: >
    1. De acordo com o problema crie um documento com soluções para o problema: {problema}.
    2. As seções e subtítulos devem ser nomeados de maneira envolvente
    3. Caso o problema não seja de sua área não faça nada
  expected_output: >
    Caso o problema seja de sua área, envie esse documento para o Supervisor de artigos
  agent: tecnico
  

supervisar:
  description: >
    1. Corrigir possíveis erros gramaticais do documento sobre o problema: {problema}.
    2. Corrigir também erros jurídicos e técnicos.
    3. Caso o problema não seja da área de Telecomunicações apague o texto anterior do documento e escreva que o problema está fora do escopo no documento
  expected_output: >
    Um documento com soluções bem escrito, em português do Brasil, com cada seção contendo 3 ou 4 parágrafos. Ao final, as referências utilizadas no documento.
  agent: supervisor